Promise.resolve(1)  //проміс перехдить в стан fulfilled з результатом "1"
		.then((x) => x + 1) //then отримує результат виконання промісу та додає до нього 1, результат виконання промісу буде = 2
		.then((x) => { throw new Error('My Error') }) //результат виконання промісу зміниться на "My Error" який ми передємо далі (якщо прибрати наступні етапи виконання у ланцюгу то код впаде)
		.catch(() => 1) //ми відловили помилку та повернули 1 як результат виконання промісу
		.then((x) => x + 1) // ми додали до результата викоання промісу 1 та отримали 2
		.then((x) => console.log(x)) // виводимо результат виконання промісу в консоль
		.catch(console.error) //не спрацює тому що ми не отримаємо помилку, якщо видалили все до 3 строки та передати сюди помилку ми побачимо ії у консолі (код не впаде)